cities = {"Addis Ababa" : "Ethiopia",
"Antananarivo" : "Madagascar",
"Asmara" : "Eritrea",
"Blantyre" : "Malawi",
"Bujumbura" : "Burundi",
"Dar es Salaam" : "Tanzania",
"Dire Dawa" : "Ethiopia",
"Djibouti City" : "Djibouti",
"Dodoma" : "Tanzania",
"Gitega" : "Burundi",
"Harare" : "Zimbabwe",
"Hargeisa" : "Somaliland",
"Juba" : "South Sudan",
"Kampala" : "Uganda",
"Keren" : "Eritrea",
"Kigali" : "Rwanda",
"Kisumu" : "Kenya",
"Kitwe" : "Zambia",
"Lilongwe" : "Malawi",
"Lindi" : "Tanzania",
"Lusaka" : "Zambia",
"Mahajanga" : "Madagascar",
"Malakal" : "South Sudan",
"Mamoudzou" : "Mayotte",
"Maputo" : "Mozambique",
"Mbarara" : "Uganda",
"Mogadishu" : "Somalia",
"Mombasa" : "Kenya",
"Muhanga" : "Rwanda",
"Moroni" : "Comoros",
"Mutsamudu" : "Comoros",
"Muyinga" : "Burundi",
"Mwanza" : "Tanzania",
"Nacala" : "Mozambique",
"Nairobi" : "Kenya",
"Ngozi" : "Burundi",
"Port Louis" : "Mauritius",
"Saint-Denis" : "Réunion",
"Saint-Paul" : "Réunion",
"Victoria" : "Seychelles",
"Zanzibar City" : "Tanzania"}
countries_africa = {"Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi","Cameroon","Cape Verde","Central African Republic",
"Chad","Comoros","Congo","Cote d'Ivoire","Democratic Republic of Congo","Djibouti","Egypt","Equatorial Guinea","Eritrea",
"Eswatini (Swaziland)","Ethiopia","Gabon","Gambia","Ghana","Guinea","Guinea-Bissau","Kenya","Lesotho","Liberia","Libya",
"Madagascar","Malawi","Mali","Mauritania","Mauritius","Mayotte","Morocco","Mozambique","Namibia","Niger","Nigeria","Réunion",
"Rwanda","Saint Helena","São Tomé and Príncipe","Senegal","Seychelles","Sierra Leone","Somalia","South Africa","South Sudan",
"Sudan","United Republic of Tanzania","Togo","Tunisia","Uganda","Zambia","Zimbabwe",}
print(len(countries_africa))
for x in countries_africa:
    print(x, "is a beautiful country in Africa")
